
[package]
name = "y_2024"
version = "0.1.0"
edition = "2024"

[dependencies]
advent_core = { path = "../../advent_core" }
macros = { path = "../../macros" }
rayon = "1.11.0"
regex = "1.12.2"
utils = { path = "../../utils" }
