[package]
name = "advent_core"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.18.3"
regex = "1.12.2"
advent-hack = { version = "0.1", path = "../advent-hack" }
